schema_objects_path:
  vk_schema/objects.json
schema_methods_path:
  vk_schema/methods.json
schema_responses_path:
  vk_schema/responses.json
object_models_imports:
  enum:
    null
  inspect:
    null
  typing:
    null
  pydantic:
    - BaseModel
object_methods_imports:
  typing:
    null
  .base_category:
    - BaseCategory
object_responses_imports:
  inspect:
    null
  typing:
    null
  .base_response:
    - BaseResponse
