schema_objects_path:
  config/objects.json
schema_methods_path:
  config/methods.json
object_models_imports:
  enum:
    None
  typing:
    - Any
    - List
    - Optional
    - Union
  pydantic:
    - BaseModel
